version: "3.9"
services:
  postgres:
    image: postgres:17
    container_name: leetcode_pg17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: leetcode
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./problems:/problems  # Mount problems directory
    command: >
      postgres -c track_io_timing=on
               -c shared_preload_libraries=pg_stat_statements
               -c pg_stat_statements.max=10000
               -c pg_stat_statements.track=all

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: leetcode_pgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:
