name: Java CI
on:
  push:
    branches: [ main, master, develop, "**/feat/**", "**/feature/**", "**/fix/**", "**/bug/**"]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'
          cache: 'maven'
      - name: Build & Test
        run: mvn -q clean verify
